samplesheet: config/samples.tsv

bwa:
  index: /ceph/project/goodwin/albrecht/bwa_index/results/genome

genome:
  fasta: /ceph/project/goodwin/albrecht/reference_genome/results/genome.fa

bcftools:
  targets: /ceph/project/goodwin/albrecht/notebooks/gene_regions.bed
