samplesheet: config/samples.tsv

gtf: /ceph/project/goodwin/albrecht/cellranger_mkref/results/cellranger_mkref/genes/genes.gtf.gz

experiment:
  # main title for all plots
  title: "Round 1 - run 2 (20240925_run_2)"

filter:
  barcodes:
    umi_min: 2500
    genes_min: 1000
