cellranger:
  mkref:
    fasta: /ceph/project/goodwin/albrecht/reference_genome/results/genome/genome.fa.gz
    gtf: /ceph/project/goodwin/albrecht/reference_genome/results/genome/genome.gtf.gz
    genome: BDGP_6_46
